kjdsnksjfdslk

## Shaon

In [73]:
import numpy as np

In [74]:
arr = [1, 2, 3, 4, 5]
arr

[1, 2, 3, 4, 5]

In [75]:
b = 2
b

2

In [76]:
arr + b

TypeError: can only concatenate list (not "int") to list

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1 + b

array([3, 4, 5, 6, 7])

In [ ]:
arr2 = np.array([
    [1,2,3,4],
    [2,3,4,5]
    ])
arr2


array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
arr1.ndim

1

In [ ]:
arr2.ndim

2

In [ ]:
arr1.shape

(5,)

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
b = 2.5

In [ ]:
arr = np.array([1, 2, 4.3])

arr.dtype

dtype('float64')

In [ ]:
arr3 = np.array([1, 2, 3.4, 'Hello'])
arr3.dtype

dtype('<U32')

In [ ]:
arr = np.array([1, 2, 300])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1, 2, 300], dtype = np.float16)
arr.dtype

dtype('float16')

In [ ]:
arr2 = arr.astype(np.int32)
arr2.dtype

dtype('int32')

In [ ]:
arr = np.array([1, 2, 3.2], dtype=np.int64)
arr.dtype

dtype('int64')

In [ ]:
arr

array([1, 2, 3])

In [ ]:
list1 = [1,2,3,4,5]

list1

[1, 2, 3, 4, 5]

In [ ]:
list1.append(2)

In [ ]:
list1

[1, 2, 3, 4, 5, 2]

In [ ]:
list1.remove(1)
list1

[2, 3, 4, 5, 2]

In [ ]:
list1.insert(2,0)
list1

[2, 3, 0, 0, 0, 4, 5, 2]

In [ ]:
arr = np.array([1,2 ,3 ,4])
arr

array([1, 2, 3, 4])

In [ ]:
list1 = [1,2 , 3, 4,5 , 6]

arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
set1 = {2,2,2,3,5,6}

arr1 = np.array(set1)
arr1

array({2, 3, 5, 6}, dtype=object)

In [ ]:
dc = {'a': 10, 'b': 20, 'c': 30}

dc

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
dc.keys()

dict_keys(['a', 'b', 'c'])

In [ ]:
dc.values()

dict_values([10, 20, 30])

In [ ]:
dc.items()

dict_items([('a', 10), ('b', 20), ('c', 30)])

In [ ]:
arr = np.zeros((2,3))

arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones((2,3))

arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.empty((4,3))
print(arr)

[[1.58260726e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 2.14321575e-312 2.80427159e-032]
 [1.71636591e+185 4.08595814e+179 3.53978289e-057]
 [1.32632734e-047 6.23126797e-038 2.70048797e-056]]


In [77]:
arr = np.empty((4,3))
print(arr)

[[1.58260726e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 2.14321575e-312 2.80427159e-032]
 [1.71636591e+185 4.08595814e+179 3.53978289e-057]
 [1.32632734e-047 6.23126797e-038 2.70048797e-056]]


In [80]:
arr = np.empty((4,3), dtype=np.int8)
print(arr)

[[1 1 0]
 [0 1 1]
 [1 1 1]
 [1 1 1]]


In [81]:
arr = np.full((4,3), np.inf)
print(arr)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [83]:
arr = np.random.rand(2,3)
arr

array([[0.3262668 , 0.05657063, 0.91069584],
       [0.90869298, 0.92031227, 0.45488119]])

In [93]:
arr = np.random.randint(1,10,(3,4))
arr

array([[6, 7, 6, 7],
       [5, 1, 3, 8],
       [6, 6, 1, 1]], dtype=int32)

In [95]:
arr = np.random.uniform(1.5,10.10,(3,4))
arr

array([[ 3.54218817,  8.1093809 ,  5.24385105,  6.84629689],
       [ 7.36453762,  5.71386379,  1.9050358 ,  4.46102754],
       [10.09162487,  5.96820137,  7.67098833,  4.09741786]])

In [104]:
arr = np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [105]:
arr.shape

(15,)

In [106]:
arr = arr.reshape(3,5)

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [107]:
arr = np.linspace(0,4,6)
arr

array([0. , 0.8, 1.6, 2.4, 3.2, 4. ])

In [108]:
arr = np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [111]:
arr1 = np.diag((2,3,5))
arr1

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [113]:
arr1 = np.eye(5)
arr1 = arr1.astype(np.int64)
arr1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [116]:
arr2 = np.eye(3,5,3)
arr2

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [122]:
arr = np.array([[1, 2, 3],
 [4, 5, 6]])

arr[arr > 1]

array([2, 3, 4, 5, 6])