In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import TargetEncoder

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, SVR
from sklearn.cluster import KMeans

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import silhouette_score

In [5]:
df = pd.read_csv("F:\Jupyter Projects\Phitron AL ML\Dataset\creditcard.csv")
df.shape

<>:1: SyntaxWarning: invalid escape sequence '\J'
<>:1: SyntaxWarning: invalid escape sequence '\J'
C:\Users\HP\AppData\Local\Temp\ipykernel_10612\47022496.py:1: SyntaxWarning: invalid escape sequence '\J'
  df = pd.read_csv("F:\Jupyter Projects\Phitron AL ML\Dataset\creditcard.csv")


(284807, 31)

In [6]:
df.sample(4)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
14999,26325.0,-0.967879,1.036219,1.064368,-0.195996,0.413190,1.083102,0.015840,0.966355,-0.565322,...,-0.060930,-0.122615,0.179214,-0.991777,-0.484934,0.202430,0.208517,0.039717,10.99,0
264305,161365.0,-0.150850,1.193782,-0.606791,-0.389173,1.336112,-0.742764,1.193698,-0.466136,0.121777,...,-0.268387,-0.237477,0.213426,0.556771,-1.535507,-0.024396,0.345815,0.222574,9.99,0
104633,69160.0,1.047611,-0.919297,0.327550,0.318922,-0.696706,0.660897,-0.615083,0.102293,-0.756948,...,-0.168638,-0.173721,-0.349626,-0.816968,0.622420,-0.186289,0.049534,0.039907,158.00,0
61612,49912.0,-0.402090,0.203785,1.901939,0.607834,-0.250422,0.621916,-0.116047,0.235368,-1.648287,...,-0.227083,0.059094,-0.085969,0.022981,-0.194941,-0.200275,0.210919,0.136414,19.99,0


In [7]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

## Question 1: What is the fraud percentage in this dataset?

In [8]:
total_transactions = len(df)
fraud_count = df['Class'].sum()
fraud_percentage = (fraud_count / total_transactions) * 100

print(f"Total transactions: {total_transactions}")
print(f"Fraud transactions: {fraud_count}")
print(f"Fraud percentage: {fraud_percentage:.4f}%")

Total transactions: 284807
Fraud transactions: 492
Fraud percentage: 0.1727%


# Question 2: Train K-Means with K=10 and calculate distance to nearest cluster center

In [9]:
# Separate features and labels
X = df.drop('Class', axis=1)
y = df['Class']

# Scale features (K-Means is distance-based, so scaling is essential)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train K-Means with K=10
kmeans = KMeans(n_clusters=10, random_state=42, n_init=10)
kmeans.fit(X_scaled)

# Get cluster centers
centers = kmeans.cluster_centers_

# Calculate distance of each point to its nearest cluster center
labels = kmeans.labels_
distances = np.linalg.norm(X_scaled - centers[labels], axis=1)

df['distance_to_center'] = distances

In [15]:
centers[[0]]

array([[ 0.06208936,  0.13949743, -0.52821284,  0.05211256, -0.47245275,
        -0.38068674,  0.06534206, -0.25831051,  0.00609561, -0.57704062,
         0.402861  , -0.26863492,  0.1921162 ,  0.14876817,  0.0222616 ,
         0.01527499, -1.74698282, -0.08212288,  1.54392999, -0.83162955,
        -0.40702736, -0.36450675, -0.53196508,  0.06600339, -0.02297417,
        -0.0677096 ,  0.3727181 , -0.02602843, -0.01787953,  0.18458939]])

In [16]:
centers

array([[ 6.20893639e-02,  1.39497429e-01, -5.28212838e-01,
         5.21125615e-02, -4.72452755e-01, -3.80686738e-01,
         6.53420649e-02, -2.58310507e-01,  6.09561167e-03,
        -5.77040624e-01,  4.02861002e-01, -2.68634917e-01,
         1.92116200e-01,  1.48768171e-01,  2.22615956e-02,
         1.52749884e-02, -1.74698282e+00, -8.21228753e-02,
         1.54392999e+00, -8.31629551e-01, -4.07027356e-01,
        -3.64506748e-01, -5.31965082e-01,  6.60033882e-02,
        -2.29741731e-02, -6.77096011e-02,  3.72718100e-01,
        -2.60284338e-02, -1.78795331e-02,  1.84589391e-01],
       [ 9.55904214e-01,  1.73822320e-01,  2.98534025e-01,
        -7.09562238e-01,  1.52251635e-01,  6.00129039e-01,
        -2.93123945e-01,  4.52393830e-01, -7.10818504e-02,
        -4.14751805e-02, -2.24540915e-01, -1.83251611e-01,
         2.17530110e-01, -2.58207730e-01, -1.93576655e-01,
        -4.01814746e-01, -1.20401431e-02,  1.31968728e-01,
        -5.62147126e-02,  5.71682399e-02, -9.65505127e-

In [10]:
distances

array([3.06088527, 2.6204433 , 6.1453086 , ..., 4.43370328, 5.50334103,
       2.97490132])

# Question 3: Set threshold at 95th percentile — how many frauds are detected?

In [11]:
# Set threshold at 95th percentile of distances
threshold = np.percentile(distances, 95)
print(f"Threshold (95th percentile): {threshold:.4f}")

# Flag points beyond threshold as anomalies
df['predicted_anomaly'] = (df['distance_to_center'] > threshold).astype(int)

# Count how many actual frauds are detected
frauds_detected = df[(df['predicted_anomaly'] == 1) & (df['Class'] == 1)].shape[0]
total_frauds = df[df['Class'] == 1].shape[0]

print(f"Total frauds in dataset: {total_frauds}")
print(f"Frauds detected as anomalies: {frauds_detected}")

Threshold (95th percentile): 6.8633
Total frauds in dataset: 492
Frauds detected as anomalies: 431


# Question 4: Precision and Recall for fraud detection

In [12]:
precision = precision_score(df['Class'], df['predicted_anomaly'])
recall = recall_score(df['Class'], df['predicted_anomaly'])

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

# Optional: full confusion matrix for clarity
cm = confusion_matrix(df['Class'], df['predicted_anomaly'])
print("Confusion Matrix:\n", cm)

Precision: 0.0303
Recall: 0.8760
Confusion Matrix:
 [[270505  13810]
 [    61    431]]


# Question 5: Limitations of using K-Means for anomaly detection



Assumes spherical, equally-sized clusters – K-Means assumes clusters are round and evenly distributed. Real fraud patterns are often irregular or scattered, so this assumption doesn't always hold.

Requires choosing K in advance – The number of clusters (K=10 here) is chosen arbitrarily. A wrong K value can distort distance-based anomaly scoring.

Sensitive to feature scaling – Since K-Means relies on Euclidean distance, unscaled features (like Amount) can dominate the distance calculation and mislead the clustering.

Not designed for imbalanced data – K-Means clusters based on the majority pattern (normal transactions), so rare fraud cases may get absorbed into a normal-looking cluster instead of standing out.

Distance ≠ fraud indicator – Some frauds are designed to closely resemble normal transactions (to avoid detection), so they may end up with small distances and go undetected — meaning K-Means will inherently miss "disguised" fraud.

No probabilistic confidence – K-Means gives a hard distance value, not a probability of fraud, making it harder to justify or explain individual predictions (a concern for financial audits).

Sensitive to outliers during training – A few extreme values can shift cluster centers, distorting the boundaries used for anomaly detection.