In [3]:
print("Shaon Khan")

Shaon Khan


In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [5]:
arr.shape

(5,)

In [6]:
print(arr[1:4])

[20 30 40]


In [7]:
np.zeros(20).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.random.rand(4,3).round(2)

array([[0.5 , 0.19, 0.71],
       [0.03, 0.78, 0.9 ],
       [0.09, 0.13, 0.45],
       [0.91, 0.64, 0.79]])

In [11]:
np.random.randint(10, 100,(4,3))

array([[11, 80, 42],
       [29, 61, 23],
       [74, 67, 88],
       [49, 46, 43]], dtype=int32)

In [12]:
np.arange(10,20, 2)

array([10, 12, 14, 16, 18])

In [13]:
arr = np.array([10, 20, 30, 40, 50])

np.sum(arr)

np.int64(150)

In [14]:
np.mean(arr)

np.float64(30.0)

In [15]:
np.max(arr)

np.int64(50)

In [16]:
np.argmax(arr)

np.int64(4)

In [17]:
np.sqrt(arr).round(1)

array([3.2, 4.5, 5.5, 6.3, 7.1])

In [18]:
np.sin(np.pi/2)

np.float64(1.0)

In [19]:
np.std(arr)

np.float64(14.142135623730951)

In [20]:
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
arr[0] = 111

arr

array([[111., 111., 111.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [22]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])

print(np.sum((arr1 + arr2), axis=0))
arr1 + arr2

30


array([ 2,  4,  6,  8, 10])

In [23]:
np.std(arr1)

np.float64(1.4142135623730951)

In [24]:
np.var(arr1)

np.float64(2.0)