In [1]:
import numpy as np

In [2]:
diagonal_matrix = np.diag([1,2,3])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)


In [3]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
mat = np.eye(3,5)
print(mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [7]:
mat = np.eye(3,6,2)
print(mat)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
