In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
C = np.dot(A, B)
print(C)

[[ 4  4]
 [10  8]]


In [4]:
C = A @ B
print(C)

[[ 4  4]
 [10  8]]


In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
A = np.array([[1, 2], [3, 4]])
print(np.linalg.det(A))

-2.0000000000000004


In [7]:
A = np.array([[1, 2], [3, 4]])
invA = np.linalg.inv(A)
print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
A = np.array([[2, 1], [1, -1]])
B = np.array([8, 2])
X = np.linalg.solve(A, B)
print(X)

[3.33333333 1.33333333]


In [12]:
A = np.array([[4, -2], [1, 1]])
values, vectors = np.linalg.eig(A)
print("Eigenvalues:", values)
print("Eigenvectors:\\n", vectors)

Eigenvalues: [3. 2.]
Eigenvectors:\n [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [13]:
A = np.array([[3, 4]])
print(np.linalg.norm(A))

5.0


In [14]:
A = np.array([[1, 2], [2, 4]])
print(np.linalg.matrix_rank(A))

1


In [15]:
A = np.array([[2, 1], [1, 3]])
B = np.array([8, 18])
X = np.linalg.solve(A, B)
print(X)

[1.2 5.6]
