In [4]:
import numpy as np


arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [5]:
arr = np.array([5, 10, 15])

print(arr + 5)
print(arr * 2)

[10 15 20]
[10 20 30]


In [6]:
arr = np.array([1, 2, 3, 4])

print(arr > 2)
print(arr == 3)

[False False  True  True]
[False False  True False]


In [7]:
arr = np.array([1,2,3,5])

arr += 4

print(arr)

[5 6 7 9]


In [8]:
arr = np.array([1,2,3,4,5,9])

print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

24
4.0
2.581988897471611
1
9


In [9]:
angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [10]:
arr = np.array([1, 2, 3])

print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


In [11]:
print(np.log(arr))

[0.         0.69314718 1.09861229]


In [12]:
print(np.log10(arr))

[0.         0.30103    0.47712125]


In [14]:
arr = np.array([1.2, 2.6, 3.9])

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

powers = np.array([2, 3, 4])
print(np.power(powers,2))

[1. 3. 4.]
[1. 2. 3.]
[2. 3. 4.]
[ 4  9 16]
