In [1]:
import numpy as np

arr = np.random.randint(1,50,(4,5))
print(arr)

[[47  3 26 32 14]
 [ 9 25 17 35 21]
 [19 36 45 22 29]
 [44 27  5 33  9]]


In [9]:
arr1 = np.ravel(arr)
print(arr1)

print('_' * 80)

print(arr)

print('_' * 80)

arr2 = np.ravel(arr, order='F')
print(arr2)

print('_' * 80)

arr2 = np.ravel(arr, order='C')
print(arr2)

[47  3 26 32 14  9 25 17 35 21 19 36 45 22 29 44 27  5 33  9]
________________________________________________________________________________
[[47  3 26 32 14]
 [ 9 25 17 35 21]
 [19 36 45 22 29]
 [44 27  5 33  9]]
________________________________________________________________________________
[47  9 19 44  3 25 36 27 26 17 45  5 32 35 22 33 14 21 29  9]
________________________________________________________________________________
[47  3 26 32 14  9 25 17 35 21 19 36 45 22 29 44 27  5 33  9]


In [10]:
np.sin(np.pi/2)

np.float64(1.0)

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
