In [1]:
import numpy as np

arr = np.array([5, 1, 8, 3, 2])

sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 5 8]


In [2]:
arr

array([5, 1, 8, 3, 2])

In [3]:
arr.sort()

In [4]:

arr

array([1, 2, 3, 5, 8])

In [10]:
arr = np.array([
  [12,8,10],
  [3,1,8]
])

print(arr)

np.sort(arr, axis = 1)

[[12  8 10]
 [ 3  1  8]]


array([[ 8, 10, 12],
       [ 1,  3,  8]])

In [12]:
np.sort(arr, axis = 0)

array([[ 3,  1,  8],
       [12,  8, 10]])

In [13]:
arr = np.array([10,2,7,1])

desc_sorted = np.sort(arr)[::-1]

desc_sorted

array([10,  7,  2,  1])

In [15]:
arr = np.array([50, 10, 30, 20])

indices = np.argsort(arr)
print(indices)
print(arr[indices])

[1 3 2 0]
[10 20 30 50]


In [16]:
data = np.array([("Alice", 25), ("Bob", 30), ("Charlie", 20)], dtype=[('name', 'U10'), ('age', 'i4')])
print(np.sort(data, order='age'))


[('Charlie', 20) ('Alice', 25) ('Bob', 30)]


In [20]:
arr = np.array([9, 4, 7, 1, 3, 8])
part = np.partition(arr, 4)
print(part)


[1 3 4 7 8 9]


In [22]:
scores = np.array([80, 95, 70, 60, 85])
rank = np.argsort(scores)[::-1]  # descending order
print("Rank Order:", rank)
print("Top 3 Scores:", scores[rank][:3])


Rank Order: [1 4 0 2 3]
Top 3 Scores: [95 85 80]
