In [1]:
import numpy as np

In [2]:
lst = np.array([10, 20, 30, 40, 50])

values = lst[[0, 3, 1]]

print(values)

[10 40 20]


In [5]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2[[0,1],[1,2]])

[2 6]


In [6]:
print(arr2[arr2 > 1])

[2 3 4 5 6]


In [7]:
arr2[arr2 > 2] = 0

print(arr2)

[[1 2 0]
 [0 0 0]]


In [8]:
arr3 = np.array([
  [[1,2,3],
   [4,5,6]],
  [[9,8,7],
   [9,1,2]]
])

for i in np.nditer(arr3):
  print(i)

1
2
3
4
5
6
9
8
7
9
1
2
