In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.where(arr > 25)
print(indices)
print(arr[indices])

(array([2, 3, 4]),)
[30 40 50]


In [5]:
new_arr = np.where(arr > 30, 1984, 0)
print(new_arr)

[   0    0    0 1984 1984]


In [6]:
arr = np.array([3, 7, 3, 2, 9, 3])
indices = np.where(arr == 3)
print(indices)

(array([0, 2, 5]),)


In [7]:
arr = np.array([0, 2, 0, 5, 7, 0])
print(np.nonzero(arr))

(array([1, 3, 4]),)


In [9]:
arr = np.array([12, 45, 7, 22, 50])
print(np.argmax(arr)) # index of max value
print(np.argmin(arr))# index of min value

4
2


In [10]:
arr = np.array([10, 20, 30, 40, 50])

pos = np.searchsorted(arr, 35)
print(pos)

3


In [11]:
arr = np.array([10, 20, 30, 30, 40])
print(np.searchsorted(arr, 30, side='left'))
print(np.searchsorted(arr, 30, side='right'))

2
4


In [12]:
arr = np.arange(10)

condition = arr % 2 == 0

result = np.extract(condition, arr)
print(result)

[0 2 4 6 8]


In [13]:
scores = np.array([55, 72, 48, 90, 67])
passed_idx = np.where(scores >= 60)
print("Indices:", passed_idx)
print("Passed Scores:", scores[passed_idx])

Indices: (array([1, 3, 4]),)
Passed Scores: [72 90 67]
