In [2]:
import numpy as np


arr = np.random.rand(2, 3)
print(arr)

[[0.46229581 0.83626462 0.08005541]
 [0.71097126 0.08124089 0.58575143]]


In [3]:
arr = np.random.randint(1, 10, (2,3))

print(arr)

[[9 8 6]
 [9 8 8]]


In [5]:
arr = np.random.uniform(50, 100, (3,3,4))
arr = np.round(arr, 2)

print(arr)

[[[50.85 96.57 73.64 84.17]
  [58.26 84.88 95.28 88.83]
  [64.95 91.27 53.78 80.24]]

 [[71.03 77.43 80.42 62.8 ]
  [71.16 80.57 99.26 85.2 ]
  [64.13 69.12 86.41 99.81]]

 [[82.92 87.04 87.5  74.82]
  [90.83 55.21 88.89 79.27]
  [63.4  90.93 71.34 84.61]]]
