In [1]:
import numpy as np

arr = np.array([0, 1, 2, 0, 3, 0, 4])
count = np.count_nonzero(arr)
print(count)

4


In [2]:
arr = np.array([10, 20, 30, 40, 50])
count = np.count_nonzero(arr > 25)
print(count)

3


In [3]:
arr = np.array([1, 2, 3, 2, 4, 2, 5])
count = np.sum(arr == 2)
print(count)

3


In [4]:
arr = np.array([1, 2, 1, 3, 2, 1])
unique, counts = np.unique(arr, return_counts=True)
print(unique)
print(counts)

[1 2 3]
[3 2 1]


In [6]:
arr = np.array(['apple', 'banana', 'apple', 'mango', 'banana'])
unique, counts = np.unique(arr, return_counts=True)
frequency = dict(zip(unique, counts))
print(frequency)


{np.str_('apple'): np.int64(2), np.str_('banana'): np.int64(2), np.str_('mango'): np.int64(1)}


In [7]:
arr = np.array([[0, 1, 2], [3, 0, 4]])
print(np.count_nonzero(arr, axis=0))# column-wise
print(np.count_nonzero(arr, axis=1)) # row-wise

[1 1 2]
[2 2]


In [8]:
arr = np.array([10, np.nan, 5, np.nan, 8])
nan_count = np.count_nonzero(np.isnan(arr))
print(nan_count)

2


In [9]:
arr = np.array([12, 15, 18, 10, 25])
mask = arr > 15
print(mask)
print(np.sum(mask))

[False False  True False  True]
2


In [10]:
grades = np.array([55, 40, 78, 90, 30, 67])
passed = np.count_nonzero(grades >= 50)
failed = np.count_nonzero(grades < 50)
print(f"Passed: {passed}, Failed: {failed}")

Passed: 4, Failed: 2
