In [4]:
import numpy as np

lst = [10, 20, 30, 40, 50]

array = np.array(lst,dtype=np.int32)
array, array.dtype

(array([10, 20, 30, 40, 50], dtype=int32), dtype('int32'))

In [8]:
matrix = [[1, 2, 3],
          [4, 5, 6]]

arr = np.array(matrix)

arr, arr.dtype, arr.ndim, arr.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 dtype('int64'),
 2,
 (2, 3))

In [9]:
tpl = (10, 20, 30)

arr = np.array(tpl, dtype=np.int32)

arr

array([10, 20, 30], dtype=int32)

In [ ]:
st = {1, 2, 3, 3}

arr = np.array(st, dtype = np.int32)

arr

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'set'

In [11]:
st = {1, 2, 3, 3}

arr = np.array(list(st), dtype = np.int32)

arr

array([1, 2, 3], dtype=int32)

In [13]:
dc = {
  'a': 10,
  'b': 20,
  'c': 30
}

arr = np.array(list(dc.keys()))
arr

array(['a', 'b', 'c'], dtype='<U1')

In [14]:
arr = np.array(list(dc.values()))

In [16]:
arr = arr.astype(np.int16)
arr, arr.ndim

(array([10, 20, 30], dtype=int16), 1)

In [19]:
arr = np.array(list(dc.items()))
arr, arr.dtype

(array([['a', '10'],
        ['b', '20'],
        ['c', '30']], dtype='<U21'),
 dtype('<U21'))