In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2[0][2] = 100

print(arr2)

[[  1   2 100]
 [  4   5   6]]


In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

arr1_mod = arr1[1:4].copy()

print(arr1)
print(arr1_mod)

arr1[1] = 10
arr1_mod[2] = 200

print(arr1_mod)
print(arr1)

[1 2 3 4 5]
[2 3 4]
[  2   3 200]
[ 1 10  3  4  5]


In [6]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

row1 = arr2[0:1, ]
row2 = arr2[1:, ]

print(row1)
print()
print(row2)

[[1 2 3]]

[[4 5 6]]


In [8]:
col1 = arr2[:, 0:1]
col2 = arr2[:, 1:]

print(col1)

print()


print(col2)

[[1]
 [4]]

[[2 3]
 [5 6]]
