In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.shape)

reshaped = arr.reshape(2,4)
print(reshaped)

(8,)
[[1 2 3 4]
 [5 6 7 8]]


In [8]:
arr = np.arange(1, 7)

print(arr)

arr2 = arr.reshape(3, 2)
print(arr2)

print()

print(arr)

print()
arr.resize(3,2)
print(arr)


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]


In [10]:
arr = np.array([[1,2,3],
                [4,5,6]])

flat1 = arr.flatten()
flat2 = arr.ravel()

print(flat1)
print(flat2)
print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([[10, 20],
                [30, 40]])

r = arr.ravel()
r[0] = 999

print(r)
print(arr)

[999  20  30  40]
[[999  20]
 [ 30  40]]


In [13]:
arr = np.array([1,2,3])
print(arr, arr.shape)

[1 2 3] (3,)


In [17]:
expanded = np.expand_dims(arr, axis = 0)
print(expanded.shape)

(1, 3)


In [18]:
arr = np.array([[[1, 2, 3]]])

print(arr.shape)

(1, 1, 3)


In [19]:
arr = np.squeeze(arr)

print(arr.shape)

(3,)


In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b)))


[[1 2 3]
 [4 5 6]]


In [21]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [22]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [23]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(np.split(arr, 2))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [27]:
np.split(arr, [3,5])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [30]:
arr = np.array([1, 2, 3, 4, 5])

arr = np.insert(arr, 2, 99)
print(arr)

[ 1  2 99  3  4  5]


In [31]:
arr = np.delete(arr, 1)

print(arr)

[ 1 99  3  4  5]


In [32]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [33]:
arr = np.array([1.3, 3.5 , 5.7, 6])

print(arr.astype(int))

[1 3 5 6]


In [35]:
a = np.array([1, 2, 3])
b = a.view()

b[0] = 99
print(a)
print(b)

[99  2  3]
[99  2  3]


In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [43]:
X = np.arange(12)

X = X.reshape(-1,3)
print(X)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
