In [1]:
import numpy as np

In [4]:
arr = np.arange(1, 10, 1)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
mat = arr.reshape(3,3)

print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr = np.linspace(0, 4, 8)

print(arr)

[0.         0.57142857 1.14285714 1.71428571 2.28571429 2.85714286
 3.42857143 4.        ]


In [12]:
arr = np.logspace(0, 4, 6, base = 2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
