In [1]:
import numpy as np

In [3]:
arr = np.zeros((2,3), dtype = np.int8)

print(arr)

[[0 0 0]
 [0 0 0]]


In [4]:
arr2 = np.zeros_like(arr)
print(arr2)

[[0 0 0]
 [0 0 0]]


In [9]:
arr = np.ones((3, 4, 3), dtype = np.int8)
print(arr)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [10]:
arr = np.empty((4,3), dtype=np.int8)

print(arr)

[[ 48   2  62]
 [ -4 121   1]
 [  0   0   0]
 [  0   0   0]]


In [21]:
arr2 = np.empty_like(arr)

print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
arr = np.full((3,2), np.inf)

print(arr, arr.dtype)

[[inf inf]
 [inf inf]
 [inf inf]] float64


In [25]:
arr2 = np.full_like(arr, np.inf, dtype = np.float64)

print(arr2, arr2.dtype)

[[inf inf]
 [inf inf]
 [inf inf]] float64


In [26]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
arr2 = np.copy(arr)

print(arr2)

[[1 2 3]
 [4 5 6]]
