In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = 5

print(arr1 + arr2)

[6 7 8]


In [3]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([10,20,30])

print(A+B)

[[11 22 33]
 [14 25 36]]


In [4]:
A = np.array([
  [[1],[2],[3]]
])
B = np.array([[10, 20, 30]])

C = A + B

print(A.shape)
print(B.shape)
print(C.shape)

print(C)

(1, 3, 1)
(1, 3)
(1, 3, 3)
[[[11 21 31]
  [12 22 32]
  [13 23 33]]]


In [6]:
arr = np.array([1,2,3])

print(arr.shape)

arr_col = arr[:, np.newaxis]
print(arr_col.shape)

(3,)
(3, 1)


In [8]:
arr = np.array([1,2,3])

new_arr = np.expand_dims(arr, axis = 0)
print(new_arr.shape)

new_arr = np.expand_dims(arr, axis = 1)
print(new_arr.shape)

(1, 3)
(3, 1)


In [12]:
arr = np.array([1, 2, 3])

result = np.broadcast_to(arr, (3,3))
print(result)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
titled = np.tile(arr, (2,3))
print(titled)

[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [16]:
X = np.array([[10,20,30],[40,50,60]])

mean = np.mean(X, axis=0)
print(mean)
normalized = X - mean
print(normalized)

[25. 35. 45.]
[[-15. -15. -15.]
 [ 15.  15.  15.]]


In [17]:
X = np.array([[1,2,3],[4,5,6]])

scales = np.array([1,10,100])
scaled = X * scales
print(scaled)

[[  1  20 300]
 [  4  50 600]]
