In [1]:
import numpy as np

a = np.array([1, 3, 5])
b = np.array([2, 4, 8])

print(a + b)

[ 3  7 13]


In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 'Shaon', 3],
                 [5, 6, 7]])
arr3 = np.array([
  [[1.5,2,3],
   [3,4,5]],
  [[1,1,1],
   [4,5,6]]
])

print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)
print('-' * 50)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print('-' * 50)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.dtype)

[1 2 3]
1
(3,)
int64
--------------------------------------------------
[['1' 'Shaon' '3']
 ['5' '6' '7']]
2
(2, 3)
<U21
--------------------------------------------------
[[[1.5 2.  3. ]
  [3.  4.  5. ]]

 [[1.  1.  1. ]
  [4.  5.  6. ]]]
3
(2, 2, 3)
float64


In [3]:
arr = np.array([1,2,300], dtype=np.int16)

print(arr)
print(arr.dtype)

print('_' * 50)

arr = arr.astype(np.int32)
print(arr)
print(arr.dtype)

print('_' * 50)

arr1 = np.array([3, 4, 6.6])
arr2 = arr1.astype(np.int16)
print(arr2)
print(arr2.dtype)

[  1   2 300]
int16
__________________________________________________
[  1   2 300]
int32
__________________________________________________
[3 4 6]
int16


In [4]:
lst = [1, 2, 3, 4, 5, 6]

arr = np.array(lst, dtype = np.int8)
print(arr, arr.dtype)
print('_' * 50)

lst = [10, True, 'Hello']
arr = np.array(lst)
print(arr, arr.dtype)

[1 2 3 4 5 6] int8
__________________________________________________
['10' 'True' 'Hello'] <U21


In [5]:
matrix = [[1, 2, 3],
          [6, 7, 9]]

arr = np.array(matrix, dtype = np.float16)
print(arr, arr.dtype, arr.ndim)

[[1. 2. 3.]
 [6. 7. 9.]] float16 2


In [6]:
tpl = (10, 20, 30)

arr = np.array(tpl, dtype = np.int32)

print(arr, arr.dtype)

print('_' * 50)

arr = arr.astype(np.float32)

print(arr, arr.dtype)

[10 20 30] int32
__________________________________________________
[10. 20. 30.] float32


In [7]:
arr = np.zeros((2,4), dtype=np.int8)

print(arr)

[[0 0 0 0]
 [0 0 0 0]]


In [8]:
arr2 = np.ones_like(arr)

print(arr2)

print('_' * 50)

print(arr)

[[1 1 1 1]
 [1 1 1 1]]
__________________________________________________
[[0 0 0 0]
 [0 0 0 0]]


In [9]:
arr = np.ones((2,2), dtype=np.int8)

print(arr)

print('_' * 50)

arr2 = np.zeros_like(arr)

print(arr2)

print('_' * 50)

arr = np.ones((3,2,4), dtype=np.int8)
print(arr)

print('_' * 50)

arr2 = np.ones_like(arr)
print(arr2)

[[1 1]
 [1 1]]
__________________________________________________
[[0 0]
 [0 0]]
__________________________________________________
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
__________________________________________________
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [10]:
arr = np.empty((4, 3), dtype = np.int8)

print(arr)

print('_' * 50)

arr2 = np.empty_like(arr)
print(arr2)

[[  0   0  32]
 [ 65   0   0]
 [-96  65   0]
 [  0 -16  65]]
__________________________________________________
[[  0   0  32]
 [ 65   0   0]
 [-96  65   0]
 [  0 -16  65]]


In [11]:
arr = np.full((4,3), np.inf)
print(arr)

print('_' * 50)

arr2 = np.full_like(arr, np.inf, dtype = np.float64)
print(arr2)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
__________________________________________________
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [12]:
arr = np.random.rand(2,3)

print(arr)

print('_' * 50)

arr2 = np.random.randint(1, 10, (2,3))
print(arr2)

print('_' * 50)

arr3 = np.random.randint(1957, 2011, (4,4))
print(arr3)

[[0.69473117 0.192709   0.51443551]
 [0.79907403 0.60459275 0.07755433]]
__________________________________________________
[[3 7 9]
 [9 9 6]]
__________________________________________________
[[2006 2001 1974 1982]
 [1974 1996 1966 2006]
 [1973 1984 1957 1961]
 [1973 1991 1985 2004]]


In [13]:
arr = np.random.uniform(50, 100, (3,4)).round(2)
print(arr)

[[91.53 61.34 64.04 68.53]
 [95.13 76.82 82.04 66.22]
 [80.8  95.81 94.55 71.7 ]]


In [14]:
arr = np.arange(1, 10, 1)

print(arr)

print('_' * 50)


print(np.arange(10, 50, 7))

print('_' * 50)

arr = arr.reshape(3,3)

print(arr)

print('_' * 50)

arr3 = np.linspace(0,10,15).round(2)
print(arr3)

print('_' * 100)

arr4 = np.logspace(0, 4, 6, base = 2).round(1)
print(arr4)

print('_' * 50)

arr = np.logspace(2, 6, 10, base = 5).round(1)
print(arr)

[1 2 3 4 5 6 7 8 9]
__________________________________________________
[10 17 24 31 38 45]
__________________________________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
__________________________________________________
[ 0.    0.71  1.43  2.14  2.86  3.57  4.29  5.    5.71  6.43  7.14  7.86
  8.57  9.29 10.  ]
____________________________________________________________________________________________________
[ 1.   1.7  3.   5.3  9.2 16. ]
__________________________________________________
[   25.     51.1   104.5   213.7   437.1   893.7  1827.5  3736.9  7641.3
 15625. ]


In [15]:
dia_mat = np.diag([1,2,3,4])

print(dia_mat)
print(dia_mat.shape)

print('_' * 50)


ano_dia = np.diag([1,2,3])

print(ano_dia)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)
__________________________________________________
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [16]:
identity_mat = np.eye(3)

print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
mat = np.eye(3,4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [18]:
mat = np.eye(3, 5, 2)
print(mat)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

arr2[0][1] = 44

print(arr2)

[[ 1 44  3  4]
 [ 5  6  7  8]]


In [20]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1_mod = arr1[1:4].copy()

arr1[1] = 22
arr1_mod[2] = 200

print(arr1_mod)
print(arr1)

[  2   3 200]
[ 1 22  3  4  5]


In [21]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

row_0 = arr2[0:1,]
row_1 = arr2[1:,]

print(row_0)
print(row_1)

[[1 2 3]]
[[4 5 6]]


In [22]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

col_0 = arr2[::,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print('_' * 50)

print(col_1)

[[1]
 [4]]
__________________________________________________
[[2]
 [5]]


In [23]:
lst = np.array([10, 20, 30, 40, 50])

values = lst[[0, 1, 4]]
print(values)

[10 20 50]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.shape)

reshaped = arr.reshape(2,3)
print(reshaped)

(6,)
[[1 2 3]
 [4 5 6]]


In [25]:
arr = np.arange(6)

arr2 = arr.reshape(3,2)
print(arr2)

arr.resize(2, 3)
print(arr)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [26]:
arr = np.array([[1,2],[3,4]])

flat1 = arr.flatten()
flat2 = arr.flatten()

print(flat1)
print(flat2)

[1 2 3 4]
[1 2 3 4]


In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b)))# 2-D vertical stack
print(np.hstack((a, b))) # horizontal join
print(np.vstack((a, b))) # vertical join


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

arr2 = arr.reshape(2,3)
print(arr2,arr2.shape)

(6,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [32]:
arr = np.arange(6)
print(arr)

arr2 = arr.reshape(3,2)
print(arr2)
print('_' * 50)
arr.resize(3,2)
print(arr)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
__________________________________________________
[[0 1]
 [2 3]
 [4 5]]


In [36]:
arr = np.array([[1,2,3],[4,5,6]])
flat1 = arr.flatten()
print(flat1)
flat1[1] = 10
print(flat1, arr)

print('_' * 50)

flat2 = arr.ravel()
print(flat2)

flat2[2] = 10
print(flat2, arr)

[1 2 3 4 5 6]
[ 1 10  3  4  5  6] [[1 2 3]
 [4 5 6]]
__________________________________________________
[1 2 3 4 5 6]
[ 1  2 10  4  5  6] [[ 1  2 10]
 [ 4  5  6]]


In [40]:
arr = np.array([1, 2, 3])
print(arr.shape)

print('_' * 50)

expanded = np.expand_dims(arr, axis = 0)

print(expanded, expanded.shape)

(3,)
__________________________________________________
[[1 2 3]] (1, 3)


In [41]:
arr = np.array([[[1, 2, 3]]])
print(arr.shape)

arr = np.squeeze(arr)
print(arr.shape)

(1, 1, 3)
(3,)


In [44]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a,b)))

print('_' * 50)

print(np.hstack((a,b)))

print('_' * 50)

print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]
__________________________________________________
[1 2 3 4 5 6]
__________________________________________________
[[1 2 3]
 [4 5 6]]


In [48]:
arr = np.arange(10)
print(np.split(arr, 2))

print('_' * 70)

print(np.split(arr, [3,7]))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
______________________________________________________________________
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


In [49]:
arr = np.array([1, 2, 3, 4])
arr = np.insert(arr, 2, 99)
print(arr)

print('_' * 50)

arr = np.delete(arr, 1)
print(arr)

[ 1  2 99  3  4]
__________________________________________________
[ 1 99  3  4]


In [50]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [51]:
arr = np.array([1.2, 3.5, 4.9])

print(arr.astype(int))

[1 3 4]


In [52]:
a = np.array([1, 2, 3])
b = a.view()

b[0] = 99
print(a)

[99  2  3]


In [53]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [54]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 * arr2)

[11 22 33 44]
[ 10  40  90 160]


In [55]:
arr = np.array([5, 10, 15])
print(arr + 5)

[10 15 20]


In [57]:
arr = np.array([5, 10, 15, 20, 25])
print(arr > 15)
print(arr[arr > 15])

[False False False  True  True]
[20 25]


In [58]:
arr = np.array([1, 2, 3])
arr += 5
print(arr)

[6 7 8]


In [59]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

15
3.0
1.4142135623730951
1
5


In [63]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles).round(2))

[0. 1. 0.]


In [65]:
arr = np.array([1, 2, 3])
print(np.exp(arr))

print('_' * 60)

print(np.log(arr))

[ 2.71828183  7.3890561  20.08553692]
____________________________________________________________
[0.         0.69314718 1.09861229]


In [66]:
arr = np.array([1.2, 2.6, 3.9])

print(np.round(arr))

[1. 3. 4.]


In [69]:
print(np.floor(arr))

print(np.ceil(arr))

[1. 2. 3.]
[2. 3. 4.]


In [70]:
arr1 = np.array([1, 2, 3])
arr2 = 5

print(arr1 + arr2)

[6 7 8]


In [71]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([10, 20, 30])
print(A + B)

[[11 22 33]
 [14 25 36]]


In [72]:
A = np.array([
  [[1],
   [2],
   [3]]
])

B = np.array([[10, 20, 30]])

C = A + B
print(C.shape)
print(C)

(1, 3, 3)
[[[11 21 31]
  [12 22 32]
  [13 23 33]]]


In [74]:
arr = np.array([1, 2, 3])
print(arr.shape)

arr_col = arr[:, np.newaxis]
print(arr_col, arr_col.shape)

(3,)
[[1]
 [2]
 [3]] (3, 1)


In [77]:
arr = np.array([1, 2, 3])

print(arr)
print('_' * 50)

new_arr = np.expand_dims(arr, axis=0)
print(new_arr)

print('_' * 50)
new_arr_2 = np.expand_dims(arr,axis=1)
print(new_arr_2)

[1 2 3]
__________________________________________________
[[1 2 3]]
__________________________________________________
[[1]
 [2]
 [3]]


In [78]:
arr = np.array([1, 2, 3])
result = np.broadcast_to(arr, (3,3))
print(result)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [79]:
arr = np.array([1, 2, 3])

tiled = np.tile(arr, (2,3))
print(tiled)

[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [81]:
X = np.array([[10, 20, 30],[40, 50, 60]])

mean = np.mean(X, axis=0)
print(mean)

print('_' * 60)

mean = np.mean(X, axis=1)
print(mean)

[25. 35. 45.]
____________________________________________________________
[20. 50.]


In [82]:
arr = np.array([10, 20, 30, 40])
print(arr > 25)

[False False  True  True]


In [83]:
arr = np.array([10, 20, 30, 40, 50, 60])

result = np.logical_and(arr > 10, arr < 25)
print(result)
print(arr[result])

[False  True False False False False]
[20]


In [84]:
arr1 = np.logical_or(arr < 15, arr > 35)
print(arr1)
print(arr[arr1])

[ True False False  True  True  True]
[10 40 50 60]
