In [26]:
import numpy as np

In [27]:
A = np.array([1,2,3])

print(A.ndim, A.shape)

print('_' * 50)

A = np.array([[1,2,3],
              [4,5,6]])

print(A.ndim, A.shape)

print('_' * 50)

A = np.array([[[1,2,3],
              [4,5,6]],
              [[1,2,3],
              [4,5,6]],
              [[1,2,3],
              [4,5,6]]
              ])

print(A.ndim, A.shape)


1 (3,)
__________________________________________________
2 (2, 3)
__________________________________________________
3 (3, 2, 3)


In [28]:
A = np.zeros((3,3))

print(A)

print('_' * 50)

A = np.ones((2,5))

print(A)

print('_' * 50)

A = np.ones((2,5))

print(A)

print('_' * 50)

A = np.full((3,3), 7)

print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
__________________________________________________
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
__________________________________________________
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
__________________________________________________
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [29]:
A = np.arange(10, 50)

print(A[A % 2 == 0])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [30]:
A = np.arange(0,16).reshape((4,4))

print(A)

print('_' * 50)

print(A[::, :1])

print('_' * 50)

print(A[::, 3:])

print('_' * 50)

print(A[1:3, 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
__________________________________________________
[[ 0]
 [ 4]
 [ 8]
 [12]]
__________________________________________________
[[ 3]
 [ 7]
 [11]
 [15]]
__________________________________________________
[[ 5  6]
 [ 9 10]]
