In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cpu


In [6]:
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

PyTorch version: 2.11.0+cpu
CUDA available: False
CUDA version: None


In [7]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU for computations.")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. You will be using CPU for computations.")
    # print(f"Device name: {torch.cuda.get_device_name(0)}")

CUDA is not available. You will be using CPU for computations.


In [8]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
type(a)

torch.Tensor

In [10]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [22]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [23]:
torch.tensor([[1,2,3],
              [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
torch.arange(0,10,0.5)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [27]:
torch.linspace(0,10,20)

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [30]:
x = torch.tensor([[1,2,3],[3,4,5]])
x.shape

torch.Size([2, 3])

In [31]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [32]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [35]:
torch.tensor([1.2,3.4]).dtype

torch.float32

In [36]:
torch.tensor([1.2,3.4], dtype=torch.int16)

tensor([1, 3], dtype=torch.int16)

In [37]:
torch.tensor([[1,2,3],[3,4,5]]) + 2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [38]:
torch.clamp(torch.tensor([[1,2,3],[3,4,5]]), min=2, max=4)

tensor([[2, 2, 3],
        [3, 4, 4]])

In [42]:
# ==========================================
# SIMPLE NEURAL NETWORK FROM SCRATCH
# ==========================================

# ------------------------------------------
# 1. DATA
# ------------------------------------------

X = [
    [2.0, 3.0],
    [5.0, 6.0],
    [7.0, 8.0]
]

y = [
    3.0,
    4.0,
    5.0
]


# ------------------------------------------
# 2. INITIAL WEIGHTS AND BIASES
# ------------------------------------------

# First layer
w11_1 = 0.1
w21_1 = 0.1

w12_1 = 0.1
w22_1 = 0.1

b1_1 = 0.0
b2_1 = 0.0


# Second layer
w11_2 = 0.1
w21_2 = 0.1

b_2 = 0.0


# Learning rate
lr = 0.001


# ------------------------------------------
# 3. TRAINING
# ------------------------------------------

epochs = 50

for epoch in range(epochs):

    total_loss = 0


    # Take one sample at a time
    for i in range(len(X)):

        # ----------------------------------
        # INPUT
        # ----------------------------------

        x1 = X[i][0]
        x2 = X[i][1]

        actual_y = y[i]


        # ==================================
        # FORWARD PROPAGATION
        # ==================================

        # Hidden neuron 1
        #
        # a1 = w11^1*x1 + w21^1*x2 + b1^1

        a1 = (
            w11_1 * x1
            + w21_1 * x2
            + b1_1
        )


        # Hidden neuron 2
        #
        # a2 = w12^1*x1 + w22^1*x2 + b2^1

        a2 = (
            w12_1 * x1
            + w22_1 * x2
            + b2_1
        )


        # Output
        #
        # y_hat = w11^2*a1 + w21^2*a2 + b^2

        y_hat = (
            w11_2 * a1
            + w21_2 * a2
            + b_2
        )


        # ==================================
        # LOSS
        # ==================================

        # L = (y - y_hat)^2

        loss = (actual_y - y_hat) ** 2

        total_loss += loss


        # ==================================
        # BACKPROPAGATION
        # ==================================

        # ----------------------------------
        # Step 1
        # L -> y_hat
        # ----------------------------------

        # dL/dy_hat = -2(y - y_hat)

        dL_dyhat = -2 * (actual_y - y_hat)


        # ----------------------------------
        # Step 2
        # y_hat -> output weights
        # ----------------------------------

        # dL/dw11^2
        dL_dw11_2 = dL_dyhat * a1

        # dL/dw21^2
        dL_dw21_2 = dL_dyhat * a2

        # dL/db^2
        dL_db_2 = dL_dyhat


        # ----------------------------------
        # Step 3
        # y_hat -> a1 and a2
        # ----------------------------------

        # dL/da1
        dL_da1 = dL_dyhat * w11_2

        # dL/da2
        dL_da2 = dL_dyhat * w21_2


        # ----------------------------------
        # Step 4
        # a1 -> first layer weights
        # ----------------------------------

        # dL/dw11^1
        dL_dw11_1 = dL_da1 * x1

        # dL/dw21^1
        dL_dw21_1 = dL_da1 * x2

        # dL/db1^1
        dL_db1_1 = dL_da1


        # ----------------------------------
        # Step 5
        # a2 -> first layer weights
        # ----------------------------------

        # dL/dw12^1
        dL_dw12_1 = dL_da2 * x1

        # dL/dw22^1
        dL_dw22_1 = dL_da2 * x2

        # dL/db2^1
        dL_db2_1 = dL_da2


        # ==================================
        # WEIGHT UPDATE
        # ==================================

        # w_new = w_old - learning_rate * gradient


        # ----------------------------------
        # Second layer
        # ----------------------------------

        w11_2 = w11_2 - lr * dL_dw11_2

        w21_2 = w21_2 - lr * dL_dw21_2

        b_2 = b_2 - lr * dL_db_2


        # ----------------------------------
        # First layer
        # ----------------------------------

        w11_1 = w11_1 - lr * dL_dw11_1

        w21_1 = w21_1 - lr * dL_dw21_1

        w12_1 = w12_1 - lr * dL_dw12_1

        w22_1 = w22_1 - lr * dL_dw22_1


        # ----------------------------------
        # First layer biases
        # ----------------------------------

        b1_1 = b1_1 - lr * dL_db1_1

        b2_1 = b2_1 - lr * dL_db2_1


    # ======================================
    # EPOCH LOSS
    # ======================================

    average_loss = total_loss / len(X)

    print(
        f"Epoch {epoch + 1} "
        f"Loss = {average_loss:.4f}"
    )

Epoch 1 Loss = 14.6824
Epoch 2 Loss = 13.7374
Epoch 3 Loss = 12.5801
Epoch 4 Loss = 11.1926
Epoch 5 Loss = 9.5920
Epoch 6 Loss = 7.8466
Epoch 7 Loss = 6.0792
Epoch 8 Loss = 4.4433
Epoch 9 Loss = 3.0757
Epoch 10 Loss = 2.0486
Epoch 11 Loss = 1.3542
Epoch 12 Loss = 0.9272
Epoch 13 Loss = 0.6846
Epoch 14 Loss = 0.5549
Epoch 15 Loss = 0.4881
Epoch 16 Loss = 0.4544
Epoch 17 Loss = 0.4373
Epoch 18 Loss = 0.4283
Epoch 19 Loss = 0.4232
Epoch 20 Loss = 0.4200
Epoch 21 Loss = 0.4178
Epoch 22 Loss = 0.4161
Epoch 23 Loss = 0.4146
Epoch 24 Loss = 0.4133
Epoch 25 Loss = 0.4120
Epoch 26 Loss = 0.4108
Epoch 27 Loss = 0.4097
Epoch 28 Loss = 0.4085
Epoch 29 Loss = 0.4074
Epoch 30 Loss = 0.4063
Epoch 31 Loss = 0.4052
Epoch 32 Loss = 0.4041
Epoch 33 Loss = 0.4030
Epoch 34 Loss = 0.4019
Epoch 35 Loss = 0.4008
Epoch 36 Loss = 0.3997
Epoch 37 Loss = 0.3986
Epoch 38 Loss = 0.3976
Epoch 39 Loss = 0.3965
Epoch 40 Loss = 0.3954
Epoch 41 Loss = 0.3944
Epoch 42 Loss = 0.3933
Epoch 43 Loss = 0.3922
Epoch 44 Loss = 

In [41]:
print("\nFinal Parameters:")

print("w11^1 =", w11_1)
print("w21^1 =", w21_1)

print("w12^1 =", w12_1)
print("w22^1 =", w22_1)

print("b1^1  =", b1_1)
print("b2^1  =", b2_1)

print("w11^2 =", w11_2)
print("w21^2 =", w21_2)

print("b^2   =", b_2)


Final Parameters:
w11^1 = 0.30611115122761645
w21^1 = 0.37687593749621207
w12^1 = 0.30611115122761645
w22^1 = 0.37687593749621207
b1^1  = 0.07076478626859573
b2^1  = 0.07076478626859573
w11^2 = 0.48112268608275804
w21^2 = 0.48112268608275804
b^2   = 0.23891291324092817
