Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])

print(arr[0])
arr[1]

1


np.int64(2)

In [7]:
arr[3] + arr[2]

np.int64(7)

## Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [11]:
arr2 = np.array([[1,2,3,4],[9,8,7,6]])

print(arr2[0][1])
print(arr2[0,1])
print(arr2[1,3])

2
2
6


## Access 3-D Arrays

In [14]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3[0, 1, 0])

4


## Negative Indexing

In [16]:
arr4 = np.array([[1,2,3,4,5],[2,1,8,8,9]])

arr4[1,::-1]

array([9, 8, 8, 1, 2])

In [17]:
arr4[:,::-1]

array([[5, 4, 3, 2, 1],
       [9, 8, 8, 1, 2]])

In [21]:
arr4[0],arr4[1]

(array([1, 2, 3, 4, 5]), array([2, 1, 8, 8, 9]))

In [22]:
import numpy as np

In [23]:
arr = np.array([10,15,20,25,30])

In [25]:
print(arr[arr>20])

[25 30]


In [26]:
arr[arr % 10 == 0]

array([10, 20, 30])

In [28]:
arr[arr < 25] = 0
arr

array([ 0,  0,  0, 25, 30])

In [29]:
arr2d = np.array([[1,2,3],[4,5,6]])

arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2d[arr2d % 2 == 0]

array([2, 4, 6])