In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [2]:
arr[:5]

array([1, 2, 3, 4, 5])

In [3]:
arr[2:]

array([3, 4, 5, 6, 7])

In [4]:
arr[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [5]:
arr[2::-1]

array([3, 2, 1])

In [9]:
arr[::-2]

array([7, 5, 3, 1])

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
arr[-3:-1]

array([5, 6])

In [12]:
arr[1:5:2]

array([2, 4])

In [13]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [15]:
arr1[1,1:4]

array([7, 8, 9])

In [24]:
arr1[0:2,1]

array([2, 7])

In [25]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr1[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [28]:
import numpy as np

In [30]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr[0][1]

np.int64(2)

In [31]:
print(arr[1])

[4 5 6]


In [32]:
print(arr[:,2])

[3 6 9]


In [33]:
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


In [37]:
print(arr[2, ::-1])

[9 8 7]
