In [1]:
import numpy as np

arr = np.array([1,2,3])

for x in arr:
  print(x)

1
2
3


In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [5]:
for x in arr:
  for y in x:
    print(y,end=" ")
  print()

1 2 3 
4 5 6 


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [7]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [11]:
for x in arr:
  for y in x:
    for z in y:
      print(z,end=" ")
    print()


1 2 3 
4 5 6 
7 8 9 
10 11 12 


In [14]:
arr = np.array([[[1,2,3],[2,3,5]],[[9,0,1],[7,5,1]]])

for x in np.nditer(arr):
  print(x,end=" ")

1 2 3 2 3 5 9 0 1 7 5 1 

In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


In [16]:
arr = np.array([1, 2, 3])

for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [17]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
