In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y = np.array([1,2,3])

X + Y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [3]:
X * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
row_mean = X.mean(axis=1,keepdims=True)
row_mean

array([[2.],
       [5.],
       [8.]])

In [6]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
row_mean

array([[2.],
       [5.],
       [8.]])

In [5]:
X - row_mean

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])