In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

In [3]:
h = np.concatenate((a,b),axis=0)

In [5]:
h,h.shape

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 (4, 2))

In [6]:
v = np.concatenate((a,b),axis=1)
v,v.shape

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 (2, 4))

In [7]:
s = np.stack((a,b),axis=0)

In [12]:
s,s.ndim,s.shape

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 3,
 (2, 2, 2))

In [13]:
c = np.column_stack((a,b))
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])