## The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

x = arr.copy()
arr[0] = 42

x, arr

(array([1, 2, 3, 4, 5, 6]), array([42,  2,  3,  4,  5,  6]))

In [3]:
arr1 = np.array([1,2,3,4,5,6])
x1 = arr1.view()

arr1[0] = 22

print(x1,arr1)

x1[1] = 100

print(x1,arr1)

[22  2  3  4  5  6] [22  2  3  4  5  6]
[ 22 100   3   4   5   6] [ 22 100   3   4   5   6]


In [4]:
arr3 = np.array([1,2,3,4,4,4])

x = arr3.copy()
y = arr3.view()

x.base,y.base

(None, array([1, 2, 3, 4, 4, 4]))

| Method   | Memory      |
| -------- | ----------- |
| `copy()` | নতুন memory |
| `view()` | একই memory  |
