NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,7])

arr,type(arr)

(array([1, 2, 3, 4, 5, 6, 7, 7]), numpy.ndarray)

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [2]:
arr2 = np.array((1,2,3,4,5,6))

arr2,type(arr2)

(array([1, 2, 3, 4, 5, 6]), numpy.ndarray)

In [3]:
arr3 = np.array(100)

arr,type(arr)

(array([1, 2, 3, 4, 5, 6, 7, 7]), numpy.ndarray)

| Code              | Array Type   | Dimension | Shape  |
| ----------------- | ------------ | --------- | ------ |
| `np.array(100)`   | Scalar array | 0D        | `()`   |
| `np.array([100])` | Vector       | 1D        | `(1,)` |


In [4]:
arr3.shape

()

In [5]:
arr3.ndim

0

## 1-D Arrays

In [6]:
arr4 = np.array([100])

arr4,type(arr4),arr4.shape,arr4.ndim

(array([100]), numpy.ndarray, (1,), 1)

## 2-D Arrays

In [9]:
arr5 = np.array([[1,2,4,5,6],[9,8,7,6,1]])

arr5

array([[1, 2, 4, 5, 6],
       [9, 8, 7, 6, 1]])

## 3-D arrays

In [10]:
arr6 = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[1,5,9]]])

arr6

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [1, 5, 9]]])

In [11]:
arr6.ndim

3

In [15]:
arr7 = np.array([1,2,3,4],ndmin=8)

arr7,arr7.ndim

(array([[[[[[[[1, 2, 3, 4]]]]]]]]), 8)

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4])
print(arr1, arr1.dtype)
print(arr1.dtype)

[1 2 3 4] int64
int64


In [13]:
arr2 = np.zeros((2,3))  # 2 rows, 3 columns
arr3 = np.ones((2,3),dtype=int)


arr2,arr3

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1, 1, 1],
        [1, 1, 1]]))

In [17]:
arr4 = np.arange(0,10,3)

arr4

array([0, 3, 6, 9])

In [22]:
arr5 = np.linspace(0,1,5)
arr5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])