## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [8]:
import numpy as np

arr = np.array([1,2,3,4,5,6,6,7,8])

type(arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('int64')

In [10]:
arrS = np.array(['Shaon','Khan',"Nahid","Mahi"])

arrS

array(['Shaon', 'Khan', 'Nahid', 'Mahi'], dtype='<U5')

In [11]:
arrS.dtype

dtype('<U5')

In [15]:
arr2 = np.array([1,2,3,4])

arr,arr.dtype

(array([1, 2, 3, 4, 5, 6, 6, 7, 8]), dtype('int64'))

In [16]:
arr2 + 2

array([3, 4, 5, 6])

In [17]:
arr3 = np.array([1,2,3,4],dtype='S')

arr3,arr3.dtype

(array([b'1', b'2', b'3', b'4'], dtype='|S1'), dtype('S1'))

In [18]:
arr3 + 2

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('S1'), dtype('int64')) -> None

In [22]:
arr4 = np.array([1,2,3],dtype='i')
arr4

array([1, 2, 3], dtype=int32)

In [23]:
arr5 = np.array([1.1,2,3.6])
arr5

array([1.1, 2. , 3.6])

In [24]:
type(arr5),arr5.dtype

(numpy.ndarray, dtype('float64'))

In [25]:
arr6 = arr5.astype('i')

arr6.dtype,arr6

(dtype('int32'), array([1, 2, 3], dtype=int32))

In [26]:
arr7 = np.array([2.22,3.99,8])

arr8 = arr7.astype(int)

arr8,arr8.dtype

(array([2, 3, 8]), dtype('int64'))

In [31]:
arr9 = np.array([-1,2,0,8])

arr10 = arr9.astype(bool)

print(arr10)

arr11 = arr10.astype(int)
arr11

[ True  True False  True]


array([1, 1, 0, 1])