In [2]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr2,arr1))

arr

array([4, 5, 6, 1, 2, 3])

In [7]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


arr = np.concatenate((arr1,arr2),axis = 1)

print(arr,arr.shape)


arrV = np.concatenate((arr2,arr1),axis=0)

arrV,arrV.shape

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


(array([[5, 6],
        [7, 8],
        [1, 2],
        [3, 4]]),
 (4, 2))

In [9]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2), axis = 1)

arr

array([[1, 4],
       [2, 5],
       [3, 6]])