In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
B

array([[5, 6],
       [7, 8]])

In [5]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [6]:
A * B

array([[ 5, 12],
       [21, 32]])

In [7]:
A, A.T

(array([[1, 2],
        [3, 4]]),
 array([[1, 3],
        [2, 4]]))

In [8]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [9]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [11]:
eigenvalues,eigenvectors

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))