In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50,60,70])

arr + 10

array([20, 30, 40, 50, 60, 70, 80])

In [3]:
arr * 2

array([ 20,  40,  60,  80, 100, 120, 140])

In [5]:
arr ** 2

array([ 100,  400,  900, 1600, 2500, 3600, 4900])

In [6]:
np.sum(arr)

np.int64(280)

In [7]:
np.mean(arr)

np.float64(40.0)

In [8]:
np.std(arr)

np.float64(20.0)

In [9]:
arr2d = np.array([[1,2,3],[4,5,6]])

np.sum(arr2d,axis=0)

array([5, 7, 9])

In [10]:
np.sum(arr2d,axis=1)

array([ 6, 15])