In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,3)
print(arr)


[[0.01184334 0.5395012  0.89460001]
 [0.07941969 0.59308114 0.03950576]
 [0.43866883 0.62725779 0.28928585]]


In [3]:
arr2 = np.random.randn(2,4)
print(arr2)


[[-1.59043288 -0.47655863 -0.72498995 -0.53886892]
 [ 2.36613234  0.65559995  0.41969075  0.81246885]]


In [4]:
arr3 = np.random.randint(0, 10, size=(3,4)) 
print(arr3)


[[9 1 2 6]
 [0 1 2 3]
 [3 1 9 2]]


In [6]:
arr4 = np.random.randint(1,100,size=(5,5))
arr4

array([[66, 74, 18, 57,  1],
       [37, 26, 66, 47, 62],
       [26, 26, 87, 52, 42],
       [ 2, 66, 40, 76, 75],
       [56, 65, 60, 40, 52]], dtype=int32)

In [7]:
data = np.array([[1,2],[3,4],[5,6]])
print(data)

np.random.shuffle(data)
print(data)

[[1 2]
 [3 4]
 [5 6]]
[[5 6]
 [1 2]
 [3 4]]
