In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

arr.shape,newarr.shape

((12,), (4, 3))

In [3]:
newarr2 = newarr.reshape(2,3,2)
newarr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [9]:
arr = np.array([1,2,3,4,5,6,7,8])

arr = arr.reshape(2,4).base


In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr = np.array([1,2,3,4])
newarr = arr.reshape(2,2,-1)

newarr

array([[[1],
        [2]],

       [[3],
        [4]]])

In [12]:
newarr = newarr.reshape(-1)

newarr

array([1, 2, 3, 4])

In [13]:
import numpy as np

In [14]:
arr = np.arange(12)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
arr_reshaped = arr.reshape(3,-1)

In [21]:
arr_reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr_reshaped.reshape(-1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr_reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr_reshaped.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr_reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])