In [1]:
import numpy as np

In [5]:
arr = np.array([10,3,5,7,2])

In [6]:
print(np.sort(arr)) 

[ 2  3  5  7 10]


In [7]:
arr

array([10,  3,  5,  7,  2])

In [4]:
print(np.argsort(arr))

[4 1 2 3 0]


In [8]:
print(np.argmax(arr))

0


In [9]:
print(np.max(arr))

10


In [10]:
print(np.where(arr > 5))

(array([0, 3]),)
