In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [3]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(np.mean(X))

5.0


In [5]:
print(np.mean(X, axis=0))

[4. 5. 6.]


In [6]:
print(np.mean(X, axis=1)) 

[2. 5. 8.]


In [7]:
print(np.std(X))

2.581988897471611


In [8]:
print(np.median(X, axis=0))

[4. 5. 6.]


In [11]:
print(np.corrcoef(X[0], X[1]))

[[1. 1.]
 [1. 1.]]
