In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

In [2]:
class StudentMarksDataset(Dataset):
    def __init__(self):
        # কাল্পনিক ডেটা: [পড়ার ঘণ্টা, ঘুমের ঘণ্টা] -> ফলাফল (পাস=1, ফেল=0)
        self.features = torch.tensor([
            [2.0, 8.0],
            [8.0, 6.0],
            [1.5, 9.0],
            [7.0, 7.0],
            [5.0, 6.5],
            [3.0, 7.0]
        ], dtype=torch.float32)
        
        self.labels = torch.tensor([0, 1, 0, 1, 1, 0], dtype=torch.long)

    # ডেটাসেটের মোট সাইজ কত
    def __len__(self):
        return len(self.features)

    # নির্দিষ্ট ইনডেক্সের ১টি স্যাম্পল রিটার্ন করা
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


# ২. Dataset ইনিশিয়ালাইজ করা
my_dataset = StudentMarksDataset()

# ৩. DataLoader তৈরি করা (ব্যাচ সাইজ ২ এবং shuffle চালু)
data_loader = DataLoader(dataset=my_dataset, batch_size=2, shuffle=True)

# ৪. মডেল ট্রেনিং লুপে ডেটা লোড করা
print(f"মোট ডেটা সংখ্যা: {len(my_dataset)}\n")

মোট ডেটা সংখ্যা: 6



In [3]:

for epoch in range(1):  # ১টি ইপক রান করে দেখা যাক
    print("--- Epoch 1 ---")
    for batch_idx, (batch_features, batch_labels) in enumerate(data_loader):
        print(f"Batch {batch_idx + 1}:")
        print("Features:\n", batch_features)
        print("Labels:", batch_labels)
        print("-" * 20)

--- Epoch 1 ---
Batch 1:
Features:
 tensor([[8.0000, 6.0000],
        [1.5000, 9.0000]])
Labels: tensor([1, 0])
--------------------
Batch 2:
Features:
 tensor([[3., 7.],
        [7., 7.]])
Labels: tensor([0, 1])
--------------------
Batch 3:
Features:
 tensor([[2.0000, 8.0000],
        [5.0000, 6.5000]])
Labels: tensor([0, 1])
--------------------
